### ISSUE TITLE
PlatformIO + LVGL "Hello World" for LILYGO 4.7" EPD

### ISSUE THREAD

**Issue by maxbrito500** [martinberlin/lv_port_esp32-epaper#10]
Hello,

Thank you so much for making this code available.

Was following the conversation at: https://forum.lvgl.io/t/lvgl-port-to-be-used-with-epaper-displays/5630

Your work is without doubt the most advanced library on this topic of LVGL integration. You even added patformIO instructions which I've done my best to replicate but was unfortunately not able to understand from where to get the needed files for making it work.

Would it be possible to make available a demo project for PlatformIO with a simple LVGL button being pressed?

Many thanks in advance, this would help so many people.

**Comment by martinberlin** [comment]
Thanks for your kind words @maxbrito500 
This was compiled only using ESP-IDF. It's still even some years afterwards still a work in progress only testeable with Lilygo EPD047 and now with epdiy ESP32-S3 v7.
But it was just an experiment. It was not really an idea to port to other areas like arduino-esp32 since the new epdiy S3 works at the moment only with IDF >= 5 and is so far the fastest Espressif parallel driver PCB.

The thing is that using a slow renderer does not make justice to LVGL and makes the UX mostly unusable so it's not worth it.

**Comment by martinberlin** [comment]
Closed due to lack of feedback
